# Generated by Django 3.2.7 on 2021-10-02 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_alter_listing_winning_bid'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='dateTime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
